### ISSUE TITLE
Error upon running apply.php

### ISSUE THREAD

**Issue by kabarovsky** [ThomasDepole/wordpress-child-plugin-tool#3]
Hi Thomas,

I'm getting this error when I run apply.php

Fatal error: Uncaught Error: Call to undefined function mime_content_type() in /home/vertical/public_html/wp-content/plugins/eclipse-wi-child/src/core.php:99 Stack trace: #0 /home/vertical/public_html/wp-content/plugins/eclipse-wi-child/src/core.php(94): get_file_list('/home/vertical/...', true) #1 /home/vertical/public_html/wp-content/plugins/eclipse-wi-child/src/core.php(94): get_file_list('/home/vertical/...', true) #2 /home/vertical/public_html/wp-content/plugins/eclipse-wi-child/src/core.php(94): get_file_list('/home/vertical/...', true) #3 /home/vertical/public_html/wp-content/plugins/eclipse-wi-child/src/core.php(94): get_file_list('/home/vertical/...', true) #4 /home/vertical/public_html/wp-content/plugins/eclipse-wi-child/apply.php(10): get_file_list('/home/vertical/...', true) #5 {main} thrown in /home/vertical/public_html/wp-content/plugins/eclipse-wi-child/src/core.php on line 99

Any ideas?

**Comment by SuavePlan** [comment]
You’re missing a vital php module. Try running “apt install php-mime-type” on your command line.

**Comment by ak-theinthantun** [comment]
Error upon running apply.php

Fatal error: Array and string offset access syntax with curly braces is no longer supported in C:\xampp\htdocs\wptest\wp-content\plugins\newsletter-child\src\core.php on line 85
